### PR TITLE
Allow Doctrine DBAL 3

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added support for Doctrine DBAL 3.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Not sure with any of this changes, just tried to follow deprecation messages. This bundle blocks the doctrine orm admin bundle. @phansys or @VincentLanglet do you know why test fail?

**Comment by simonberger** [comment]
@jordisala1991 The changes are looking good to me. Didn't check if they are complete.

To the tests failures it is probably this:
https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Schema/Column.php#L78-L89

Which means already a problem in the current releases and another deprecation in dbal 2.X which has to be solved.

**Comment by simonberger** [comment]
Just a side note:
I would prefer tests to fail when hitting a deprecation or at least displaying it. I saw no such output in the previous runs of PHPUnit.

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/EntityAuditBundle/pull/446 might help @jordisala1991

**Review by simonberger — CHANGES_REQUESTED** [review]
The tests are failing because of:
```php
$revisionsData = $this->em->getConnection()->executeQuery($query, $params);
```
https://github.com/sonata-project/EntityAuditBundle/pull/444/files#diff-d3e6d43afbe921b0b71e48fdc65d0402668ac18f5306f927ef57f81d3cb1d7abL459

It works in 2.13 and 3.1 like this:

```php
$revisionsData = $this->em->getConnection()->fetchAllAssociative($query, $params);
```



Alternatively do `executeQuery` with single `fetchAssociative` in a while loop.

I am still irritated why the existing code did not fail in 2.13 and when it has been changed. Some forwardCompatibility classes are executed there, so probably it was a change many versions ago which is not well documented.

**Comment by jordisala1991** [comment]
I think it would be nice to get your review too @simonberger

**Review by phansys — APPROVED** [review]

**Review by simonberger — APPROVED** [review]
Changes in this PR look good to me as well.
Approved with minor comment:

The use of the `SQLResultCasing` trait is not optimal. Changes or a removal could happen in every version.
Considering the minimal code it provides the trait probably should be copied into this library. Didn't mention it in the other PR because I thought the solution here will be different.

**Comment by jordisala1991** [comment]
> Changes in this PR look good to me as well.
> 
> Approved with minor comment:
> 
> 
> 
> The use of the `SQLResultCasing` trait is not optimal. Changes or a removal could happen in every version.
> 
> Considering the minimal code it provides the trait probably should be copied into this library. Didn't mention it in the other PR because I thought the solution here will be different.

Do you want to provide a PR with that changes? I think we can add that trait to our library too

**Pull request merged**
