### PR TITLE
Add php8

### PR DESCRIPTION
**Pull request by VincentLanglet**
I tried to install it locally, and it works fine.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
From https://github.com/simplethings/EntityAuditBundle/issues/203#issuecomment-240341383

@tolry
@beberlei
@DavidBadura
@smoench
@andrewtch
@merk

I know this project is not maintain anymore but does someone has time to merge and release this PR in order to at least still allow user to use it ?

**Comment by andrewtch** [comment]
Let's wait for Travis to pass, at least :)

**Comment by smoench** [comment]
@VincentLanglet since this bundle was published under the MIT license and it hasn't received any updates the last 3 years you are free to fork it.

As I can't recommend this bundle anymore please stop pinging me for any changes related to this project. Thanks you! :-)
Consider using EventSourcing instead ...

**Comment by VincentLanglet** [comment]
> Let's wait for Travis to pass, at least :)

Test can't run on php8 because they were written with phpunit 4.8...
It would require a lot of work to rewrite every test, and i'm not sure of the interest if the repository is not maintained.

My goal was to allow people with this dependency (for instance if they provide a bridge) to use php8.

**Comment by RobinDev** [comment]
Maybe we could skip adding PHP 8.0 to Travis and use this pattern in composer :

```
"php": ">=5.3.9",
```

**Comment by tolry** [comment]
As @smoench said, there is no active development going on.

Yesterday I spoke to @beberlei - who initially wrote this bundle - and he suggested for sonata to maybe pick up the bundle, because ~90% of the downloads for this bundle come from sonata users, since they recommend it in their [documentation](https://sonata-project.org/bundles/doctrine-orm-admin/3-x/doc/reference/audit.html)

I have no idea if they have any interest (or ressources) in working on this, but maybe that might be a good place to start a discussion?

**Comment by VincentLanglet** [comment]
> As @smoench said, there is no active development going on.
> 
> Yesterday I spoke to @beberlei - who initially wrote this bundle - and he suggested for sonata to maybe pick up the bundle, because ~90% of the downloads for this bundle come from sonata users, since they recommend it in their [documentation](https://sonata-project.org/bundles/doctrine-orm-admin/3-x/doc/reference/audit.html)
> 
> I have no idea if they have any interest (or ressources) in working on this, but maybe that might be a good place to start a discussion?

That could be an idea indeed. I don't personally use this bundle but I know that at least one of sonata maintainer does.

@wbloszyk @greg0ire @franmomu @OskarStark @phansys @dmaicher @core23 @jordisala1991 
WDYT ?

**Comment by wbloszyk** [comment]
IMHO this bundle is great to create database logs in sonata admin. I use it in some project and i wants use it in the new one. We should keep this functionality. I can help with contribiluting here or as sonata bundle.

**Comment by OskarStark** [comment]
Why not, @beberlei would it be possible to move it to our organization while keeping the packagist package name for transition phase 1 and abandon it and add a new package name under sonata scope in transition phase 2?

If yes, you can add me to the repo and give me the needed access and I will move it ▶️

**Comment by tolry** [comment]
@OskarStark I also have packagist permissions on this package and could help out with this, but I would like to check in with someone from SimpleThings first and see if that's ok with them.

**Comment by tolry** [comment]
@OskarStark I got the :green_circle: from SimpleThings to transfer the package, can I simply add someone from Sonata to the list of packagist maintainers and you'll take it from there? Just need packagist-username for that, thanks.

**Comment by OskarStark** [comment]
HI @tolry, thank you!

First I need Admin access to this repository to transfer it to sonata-project organization on github

**Comment by tolry** [comment]
@OskarStark you should have an invite

**Pull request closed without merging**
