### PR TITLE
Audit Reader , Get Field Name of ManyToOne Relation

### PR DESCRIPTION
**Pull request by tobias-nitsche**
Patch for simplethings #273

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | no
| Fixed tickets | #273

Conversion between columnName and fieldName added.

### CODE REVIEW

**Comment by tobias-nitsche** [comment]
@DavidBadura PR ist ok to you?

**Comment by DavidBadura** [comment]
@tobias-nitsche thank you for your work! Can you add a test so we can make sure that something does not happen anymore?

**Comment by tobias-nitsche** [comment]
Not that much time right now ;) Anybody else feeling free to do so? ;)

**Comment by DavidBadura** [comment]
What do you do exactly? I can't reproduce this Issue :-( https://github.com/simplethings/EntityAuditBundle/pull/292/files#diff-fa00c5fc82c33e622a901e0ca72238bcR335

**Comment by tobias-nitsche** [comment]
@DavidBadura The error occurs, when you have a many to one relation with non standard column names.

**Comment by FlorianKoerner** [comment]
Any news on this?

**Pull request closed without merging**
