### PR TITLE
Drop doctrine common

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is Bc.

Removing doctrine common, even if we still get it as a transitive dep is a good thing. If the project dont use it directly lets remove it, it is kind of being deprecated.

## Changelog

```markdown
### Removed
- Drop doctrine common dependency.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I have tried a search for doctrine common and didnt found it on the project, there are uses for Collections, Event manager, but thats on other packages.

@VincentLanglet could you do a second check just to be sure?

**Comment by phansys** [comment]
https://github.com/sonata-project/EntityAuditBundle/blob/9ffd87ebc60de3abc0cee3b95304e90c0a54f690/src/EventListener/CreateSchemaListener.php#L16

https://github.com/sonata-project/EntityAuditBundle/blob/9ffd87ebc60de3abc0cee3b95304e90c0a54f690/src/AuditManager.php#L16

**Comment by jordisala1991** [comment]
> https://github.com/sonata-project/EntityAuditBundle/blob/9ffd87ebc60de3abc0cee3b95304e90c0a54f690/src/EventListener/CreateSchemaListener.php#L16
> 
> https://github.com/sonata-project/EntityAuditBundle/blob/9ffd87ebc60de3abc0cee3b95304e90c0a54f690/src/AuditManager.php#L16

Those are here : https://github.com/doctrine/event-manager/tree/2.0.x/src

And it is already a dep for this package

**Review by phansys — APPROVED** [review]
Just confirmed, [`Doctrine\Common\EventSubscriber`](https://github.com/doctrine/event-manager/blob/fe71bc032e5de972b8d18939abfa87d23f43ebd3/src/EventSubscriber.php#L13) and [`Doctrine\Common\EventManager`](https://github.com/doctrine/event-manager/blob/fe71bc032e5de972b8d18939abfa87d23f43ebd3/src/EventManager.php#L14) are provided by `doctrine/event-manager`.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks

**Pull request merged**
