### PR TITLE
Fix columnName

### PR DESCRIPTION
**Pull request by gonzaloalonsod**
$columnName = $idKeys[0]; change by $columnName = $idField;

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | yes
| Fixed tickets | #...

### CODE REVIEW

**Comment by tolry** [comment]
@gonzakpo could you elaborate which problem you had that this PR fixes? Your fix seems to break lots of unit tests, see travis logs (e.g. https://travis-ci.org/simplethings/EntityAuditBundle/jobs/270498009) - so this seems not to be universally applicable.

**Comment by gonzakpo** [comment]
before it generated: WHERE e.rev <=? AND e.0 =?
and with e.0 it does not work for me.
then now it generates me: WHERE e.rev <=? AND e.id =?
and if it works for me.
What I can be doing wrong?

**Comment by tolry** [comment]
@gonzakpo do you have the code accessible somewhere or can you post your entity definitions?

**Comment by Webonaute** [comment]
I have the same issue, PHP7.1 with symfony 3.2.

**Comment by kevinpapst** [comment]
Same issue here with PHP 7.1.12, Symfony 3.4.3, DoctrineORM 2.6.0, Doctrine-Bundle 1.8.1
Happens when I try to view the details of an audit entry. Exception:
```
An exception occurred while executing 'SELECT e.revtype, e.id AS "id", e.name AS "name", e.comment AS "comment", e.visible AS "visible", e.company AS "company" FROM xxx_customers_audit e WHERE e.rev <= ? AND e.0 = ? ORDER BY e.rev DESC' with params ["2", "2"]:
```
The fix by @gonzakpo seems to work in my scenario.

**Comment by tolry** [comment]
Hmm, I guess this might be an incompatibility with Doctrine 2.6 - anyone here having this issue with 2.5 or lower?

Probably noone around with enough internals knowledge to give a hint what might be the issue here? As I sait: the proposed fix seems to break a few tests and probably breaks production code ... hmm

**Comment by kevinpapst** [comment]
Its good that it breaks unit tests, a sign for a well tested bundle! But if these test cover a bug, that might be a false-positive then ;-) at least with the provided software package versions. 
Let me know if I can be of any help in investigating. Unfortunately I can neither share my repo (private) nor downgrade the Doctrine packages. 

And as you said: do not simply apply the patch to the core , as it will very likely break production code for other users out-there. I just wanted to make sure that you are aware of the problem and keep an eye on it.

**Pull request closed without merging**
