### PR TITLE
Avoid deprecation with "symfony/config" >= 4.2

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A  |
|---          |---|
|Branch       |1.0|
|Bug fix?     |no |
|New feature? |no |
|BC breaks?   |no |
|Deprecations?|no |
|Tests pass?  |yes|
|Fixed tickets|n/a|
|License      |MIT|
|Doc PR       |n/a|

### CODE REVIEW

**Comment by netbull** [comment]
bump

**Comment by W0rma** [comment]
@tolry @DavidBadura Any chance to get this merged?

**Comment by tolry** [comment]
hi @W0rma, @DavidBadura and myself haven't been active here for quite some time. Not sure who is currently in charge of maintenance, maybe @sewah knows more?

**Comment by W0rma** [comment]
Can be closed since this has already been fixed in https://github.com/sonata-project/EntityAuditBundle/pull/347

**Comment by VincentLanglet** [comment]
I didn't add the BC-layer, so I'm not sure why it work with Symfony 5...

**Comment by W0rma** [comment]
Ah you are right. The bundle can not be used with symfony < 4.2 anymore because of the missing BC layer.

**Comment by VincentLanglet** [comment]
> Ah you are right. The bundle can not be used with symfony < 4.2 anymore because of the missing BC layer.

Do you want to do the PR with the fix @W0rma ?

**Comment by W0rma** [comment]
Sure, I will do it.

**Comment by VincentLanglet** [comment]
> Sure, I will do it.

https://github.com/sonata-project/EntityAuditBundle/pull/352 was merged with the drop of support for Symfony < 4.4 since these versions are not supported by Symfony anymore

**Pull request closed without merging**
