### PR TITLE
Output deprecations when running tests

### PR DESCRIPTION
**Pull request by simonberger**
In my opinion it is important to display deprecations when running tests.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I thought phpunit was already outputting deprecations when running tests. Why is there something to do with doctrine ?

**Comment by jordisala1991** [comment]
> I thought phpunit was already outputting deprecations when running tests. Why is there something to do with doctrine ?

I need to test it further but when I tried to upgrade from dbal 2 to 3 I didnt get any deprecation. 

If this is needed, Imo it should be dispatcher via dev-kit with a class_exist to avoid breaking code.

**Comment by jordisala1991** [comment]
I investigate it a bit and without this code we can't see the following deprecations:

```
Remaining indirect deprecation notices (7)

  1x: Method Doctrine\ORM\Configuration::setQueryCacheImpl() is deprecated and will be removed in Doctrine ORM 3.0. Use setQueryCache() instead. (Configuration.php:317 called by BaseTest.php:77, https://github.com/doctrine/orm/pull/9002, package doctrine/orm)
    1x in CoreTest::setUp from SimpleThings\EntityAudit\Tests

  1x: The "name" column option is not supported, setting unknown options is deprecated and will cause an error in Doctrine DBAL 3.0 (Column.php:85 called by Column.php:66, https://github.com/doctrine/dbal/pull/2846, package doctrine/dbal)
    1x in CoreTest::setUp from SimpleThings\EntityAudit\Tests

  1x: AbstractPlatform::supportsForeignKeyOnUpdate() is deprecated without replacement and removed in DBAL 3.0 (AbstractPlatform.php:3253 called by AbstractPlatform.php:2552, https://github.com/doctrine/dbal/pull/4229, package doctrine/dbal)
    1x in CoreTest::setUp from SimpleThings\EntityAudit\Tests

  1x: Connection::executeUpdate() is deprecated, use Connection::executeStatement() instead. (Connection.php:1483 called by LogRevisionsListener.php:473, https://github.com/doctrine/dbal/pull/4163, package doctrine/dbal)
    1x in CoreTest::testAuditable from SimpleThings\EntityAudit\Tests

  1x: Connection::fetchColumn() is deprecated, use Connection::fetchOne() API instead. (Connection.php:661 called by SqliteSchemaManager.php:554, https://github.com/doctrine/dbal/pull/4019, package doctrine/dbal)
    1x in CoreTest::tearDown from SimpleThings\EntityAudit\Tests

  1x: Calling Doctrine\ORM\EntityManager::flush() with any arguments to flush specific entities is deprecated and will not be supported in Doctrine ORM 3.0. (EntityManager.php:383 called by IssueTest.php:132, https://github.com/doctrine/orm/issues/8459, package doctrine/orm)
    1x in IssueTest::testIssue111 from SimpleThings\EntityAudit\Tests

  1x: Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::getCacheDriver is deprecated. Use getCache() instead. (AbstractClassMetadataFactory.php:108 called by MappedEventSubscriber.php:126, https://github.com/doctrine/persistence/issues/184, package doctrine/persistence)
    1x in IssueTest::testIssue111 from SimpleThings\EntityAudit\Tests
```

Seems like doctrine follows its own strategy to trigger deprecations. IMO it should be added as dev-kit code. Let me open a PR.

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/dev-kit/pull/1725

**Pull request closed without merging**
